package Calculator.sandbox.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.JTextField;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class My2010Rates extends JFrame {
  private DocumentListener listener = new DocumentListener() {
    public void insertUpdate(DocumentEvent p0) {
      update();
    }

    public void removeUpdate(DocumentEvent p0) {
      update();
    }

    public void changedUpdate(DocumentEvent p0) {
      update();
    }
  };
  private JTextField inputField_a = new JTextField();
  private JTextField inputField_b = new JTextField();
  private JTextField outputField_a = new JTextField();
  private JTextField outputField_b = new JTextField();
  private JTextField outputField_c = new JTextField();

  public My2010Rates() {
    setTitle("My2010Rates");
    setLayout(new GridLayout(0, 2));
    inputField_a.getDocument().addDocumentListener(listener);
    add(new JLabel("Java"));
    add(inputField_a);
    inputField_b.getDocument().addDocumentListener(listener);
    add(new JLabel("Groovy"));
    add(inputField_b);
    add(new JLabel("Output"));
    add(outputField_a);
    add(new JLabel("Output"));
    add(outputField_b);
    add(new JLabel("Output"));
    add(outputField_c);
    update();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();
    setVisible(true);
  }

  public void update() {
    int i_a = 0;
    int i_b = 0;
    try {
      i_a = Integer.parseInt(inputField_a.getText());
      i_b = Integer.parseInt(inputField_b.getText());
    } catch (NumberFormatException e) {
    }
    outputField_a.setText("" + (1 + 2 - 5 + i_b));
    outputField_b.setText("" + (i_a - i_b));
    outputField_c.setText("" + (10 + 20));
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new My2010Rates();
      }
    });
  }
}
