package Calculator.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelReference;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("Calculator", "21560302-1e32-4533-bc15-78171e32e68f"), SModelReference.fromString("r:4ce35253-7730-4e7b-9e99-93d3c9287177(Calculator.intentions)"));
  }

  public void init() {
    add(new DoubleRate_Intention(), "6766386558794101444");
  }
}
