package Calculator.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Calculator_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("21560302-1e32-4533-bc15-78171e32e68f(Calculator)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
