package Calculator.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseReferenceScopeProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class InputFieldReference_Constraints extends BaseConstraintsDescriptor {
  private static SNodePointer breakingNode_43tbk9_a0a1a0a0a1a0b0a1a0 = new SNodePointer("r:8db27b82-a96a-4e00-97fc-941f15f6f424(Calculator.constraints)", "2339873612002239834");

  public InputFieldReference_Constraints() {
    super("Calculator.structure.InputFieldReference");
  }

  @Override
  protected Map<String, ReferenceConstraintsDescriptor> getNotDefaultReferences() {
    Map<String, ReferenceConstraintsDescriptor> references = new HashMap();
    references.put("field", new BaseReferenceConstraintsDescriptor("field", this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }

      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseReferenceScopeProvider() {
          @Override
          public Object createSearchScopeOrListOfNodes(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            SNode node = SNodeOperations.getAncestor(_context.getEnclosingNode(), "Calculator.structure.Calculator", false, false);
            return SLinkOperations.getTargets(node, "inputField", true);
          }

          @Override
          public SNodePointer getSearchScopeValidatorNode() {
            return breakingNode_43tbk9_a0a1a0a0a1a0b0a1a0;
          }
        };
      }
    });
    return references;
  }
}
